### ISSUE TITLE
 as.lvs1974.NvidiaGraphicsFixup in IOKitPersonalities

### ISSUE THREAD

**Issue by Lizard1003** [acidanthera/BT4LEContiunityFixup#1]
Hello!
I just wanna tell you, what in Info.plist / Root / IOKitPersonales dictionary had name "as.lvs1974.NvidiaGraphicsFixup", instead "as.lvs1974.BT4LEContiunityFixup".
I know that this does not affect the work, just a trifle :)
Have a nice day and thank you for projects!

<img width="883" alt="2018-03-21 21 22 48" src="https://user-images.githubusercontent.com/12577060/37716059-2a1a527a-2d50-11e8-8b82-804d86fc5d34.png">

**Comment by vit9696** [comment]
Fixed
